### ISSUE TITLE
Install failing

### ISSUE THREAD

**Issue by toobulkeh** [webnuts/ember-cli-honeybadger#4]
We previously used this addon with no issues, but for some reason we recently started receiving failures from Broccoli and removed it from our package.json.

Now, we can't install it:
```console
portal top % ember install "webnuts/ember-cli-honeybadger.git"
DEPRECATION: `ember-cli/lib/errors/silent.js` is deprecated, use `silent-error` instead.
Installed packages for tooling via npm.
WARNING: Could not figure out blueprint name from: "webnuts/ember-cli-honeybadger.git". Please install the addon blueprint via "ember generate <addon-name>" if necessary.
Installed addon package.
```

```console
portal top % ember -v
ember-cli: 2.6.2
node: 6.0.0
os: darwin x64
```

Any ideas?

**Comment by martinthogersen** [comment]
Strange. Does it fail for a clean Ember Cli project?

**Comment by toobulkeh** [comment]
Hmm, no that seems to work. I'll try clearing caches and seeing what happens.

**Comment by martinthogersen** [comment]
Yeah. Try that. I'm also happy to take a look, if you upload your project on Github.

**Comment by toobulkeh** [comment]
I was able to solve this by running `ember g ember-cli-honeybadger` -- which just added the following dependency to `bower.json`: `"honeybadger.js": "^0.4.2"`. Not sure why the source command didn't work in my project anymore... but this issue is resolved. Thanks for the prompt reply!
