### ISSUE TITLE
Add to Ember Addons

### ISSUE THREAD

**Issue by bauerjon** [webnuts/ember-cli-honeybadger#5]
Hi, we'd like to use this in one of projects and install it via npm. Could you [publish to npm](https://gist.github.com/kristianmandrup/ae3174217f68a6a51ed5#publish-addon)? It would also then show up on http://www.emberaddons.com!

Thanks!

**Comment by martinthogersen** [comment]
Thanks. I'll take care of it ASAP. 👍

**Comment by martinthogersen** [comment]
Done - the plugin also appears on Ember Addons now:
https://www.npmjs.com/package/ember-cli-honeybadger

**Comment by bauerjon** [comment]
Thank you 😄
